### ISSUE TITLE
TypeError: _linear() got an unexpected keyword argument 'scope'

### ISSUE THREAD

**Issue by don-tpanic** [carpedm20/variational-text-tensorflow#6]
self.l1_lin = linear(tf.expand_dims(self.x, 0), self.embed_dim, bias=True, scope="l1")
TypeError: _linear() got an unexpected keyword argument 'scope'

Thanks in advance!

**Comment by don-tpanic** [comment]
It's always about version....

**Comment by rana-alshaikh** [comment]
@don-tpanic did you find a solution?
